### ISSUE TITLE
Feature request: Sort HashMaps if possible?

### ISSUE THREAD

**Issue by DarrenTsung** [colin-kiegel/rust-pretty-assertions#85]
Hi, thanks for the great crate.

When I use `pretty_assertions`, it's pretty difficult to get good diffing output when comparing structs that contain HashMaps because the ordering is non-deterministic.

Would it be possible to sort the diff output by the key of the HashMap (best effort)? Since the key can be printed, it has some string representation which should be sortable.

It's difficult to work around this at the usage site usually (in the trivial case, you could convert a `HashMap<_, _>` to a `Vec<(_, _)>`, but if the HashMap is within a struct then you'd need a new type(?)) and I run into this everytime I try to use `pretty_assertions`. If this would be possible, it would be huge! Or if you have any ideas how to solve the non-determinism easily, that would also be amazing 😄.

Thanks for taking the time to read my feature request 🙏🏻 .

**Comment by tommilligan** [comment]
Hmm, interesting. It's definitely something I run into a lot, and I've seen other users hit this as well.

Currently, we use the `Debug` trait to convert the data structure into a diffable string. I don't think manipulating the diffable string after it's generated is feasible, so that leaves us with a couple of options:

- use a sorted data structure before we generate the debug implementation
- generate a debug output that is sorted

Both of these have reasonably large overhead - and the issue is in treating `HashMap` as an exceptional case. I could see a path through this if, for instance, we were sorting all data that implemented `IntoIterator`. However, that's clearly not what we want for a collection like a `Vec`, where order matters.

In short, I think this is pretty complex, and could require quite a large amount of processing/memory for large data structures which `pretty_assertions` aims to not require. I think your best bet is probably something in the calling code as you mentioned:

```rust
if actual != expected {
    assert_eq!(actual.into_ordered(), expected.into_ordered());
}
```

where `into_ordered` is method that converts all your `HashMap`s into `BTreeMap`s or some such.

You could also use a newtyped hashmap to generate your own custom debug implementation:

```rust
use std::collections::HashMap;
use std::fmt;
use core::hash::Hash;


struct DebugMap<K: Hash, V>(HashMap<K, V>);

impl<K, V> fmt::Debug for DebugMap<K, V> where K: fmt::Debug + Hash + std::cmp::Ord, V: fmt::Debug {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let mut buf: Vec<_> = self.0.iter().collect();
        buf.sort_by_key(|item| item.0);
        f.debug_map().entries(buf.into_iter()).finish()
    }
}

fn main() {
    let data = DebugMap([(7, 1), (3, 3), (5, 3), (10, 3), (2, 3)].into_iter().collect());
    println!("{:?}", &data);
}
```
produces
```
{2: 3, 3: 3, 5: 3, 7: 1, 10: 3}
```
Rust playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=70c1a2d09de6541282cd7e44d9271955

**Comment by DarrenTsung** [comment]
Thanks for the detailed reply @tommilligan! I agree that we wouldn't want this for all cases, eg. sorting a vector where order matters, but would opt-in work though? I'm thinking something like:
```
rust_pretty_assertions::assert_eq_sorted_keys!(foo, bar);
```

We can also gate the logic with a feature flag.

As you can see from the mention above, I'm starting to work on a PR to implement this functionality in a fork.  It'd make this crate so much more usable for the types of tests I'm writing. Would a PR for adding it in be welcome?

Implementation-wise I'm thinking:
* Parse the debug string, if parse fails fallback to diffing the unsorted debug string.
* Sort the keys for un-ordered collections like maps
* Print the sorted debug string and diff it

**Comment by tommilligan** [comment]
I think parsing a debug string isn't the way to go, if you're looking to add a feature to this crate - you're inherently duplicating the work of printing + parsing the data. Plus, you're losing the type information that you have in the struct.

On the other hand, if it works for your use personal case, go right ahead! I'd be interested to hear how it turns out, and if you do base it on this crate fork, running some benchmarks on it would be cool.

---

As I said above, I think the best way to handle this is the layer above `pretty_assertions`, where you can convert your values to ordered structures if required. I'm not sure what the best approach here would be - but at a guess:

- you're going to want an ordered version of whatever you're working with - and you probably want to derive this automatically. So something like:

```rust
#[derive(OrderedCollections)]
struct Data {
    inner: HashMap<String, String>,
    count: u64,
}
```
derives something like
```rust
#[derive(Debug)]
struct _OrderedCollectionsData {
    inner: DebugMap<String, String>,
    count: u64,
}
```
along with an `impl` describing how to convert one into the other
```rust
impl From<Data> for _OrderedCollectionsData {
    ...
}
```

These values can then be passed to pretty assertions as usual, and you could define your own `assert_eq_ordered` macro that expands to something like:
```rust
trait IntoOrdered<T> {
    fn into_ordered(self) -> T;
}

impl<T, U> IntoOrdered for T where
    U: From<T>
{
    fn into_ordered(self) -> U {
         self.into()
    }
}

...
if actual != expected {
    assert_eq!(actual.into_ordered(), expected.into_ordered());
}
```

This is all me handwaving, I investigated adding procedural macros to `pretty_assertions` in the past, but the compile times were too long/dependency tree was too heavy to add it to the main crate. If we can offer this as a layer on top however (new crate, feature flag or whatever), might be doable.

**Comment by DarrenTsung** [comment]
Appreciate the feedback! Unfortunately procedural macros to generate an ordered version of the struct sounds a bit complicated and it seems like it would have to be derived by all nested types which isn't always feasible. 

I can build a proof of concept in a separate crate since it sounds like parsing the debug string is not your preferred solution (although I'm less worried about duplicating work if it's opt-in and only used in tests).

**Comment by DarrenTsung** [comment]
I created a crate ([pretty_assertions_sorted](https://docs.rs/pretty_assertions_sorted/latest/pretty_assertions_sorted/)) as a proof-of-concept of this. I tested it with my use-case and it works great. Hope this helps anyone with the same issue!

**Comment by gibfahn** [comment]
Hit this, tried [pretty_assertions_sorted](https://docs.rs/pretty_assertions_sorted/latest/pretty_assertions_sorted/), it worked great for my use case (simple hash map). It would be nice to have this in the pretty_assertions crate directly if possible.

**Comment by tommilligan** [comment]
Hi @gibfahn, thanks for your comment, and for checking out the project!

As I've said before I don't believe parsing, sorting and then diffing `Debug` representations is a solid enough strategy for me to be personally comfortable supporting it. As you confirmed that @DarrenTsung's crate worked for your specific case, I'm happy to consider this an edge case with a feasible workaround. Having the debug sorting as a layer on top of `pretty_assertions` 
in a new crate makes sense to me.

If there are alternate strategies or implementations in future, I'm happy to take a look in a new PR/issue :slightly_smiling_face:

**Comment by gibfahn** [comment]
I find this to be a pretty common case, but fair enough. The only real argument I'd have for inclusion in this crate is that I expect a lot of folks to need to come find this crate, find the issue, and then pull in another crate, and that crate has to be kept up-do-date with any changes to `pretty_assertions`.
